### ISSUE TITLE
Handling non-Base64 SVG images?

### ISSUE THREAD

**Issue by bjmc** [timsly/carrierwave-data-uri#2]
Hi, thanks for making this helpful plugin. One thing I noticed is that because the plugin always attempts to decode from base64, on [this line...](https://github.com/timsly/carrierwave-data-uri/blob/master/lib/carrierwave_data_uri/parser.rb#L20)

`@binary_data ||= Base64.decode64 data`

...it will wind up mangling SVG images, unless they are first base64-encoded by the user. However, there's no need to base64-encode SVGs, because they're not binary data, and in fact base64-encoding [actually makes the files somewhat larger.](https://css-tricks.com/probably-dont-base64-svg/)

As a future enhancement, it would be great if this plugin could accept normal utf8 SVG data URIs. I'm happy to submit a PR, but I probably can't get to it immediately.

For what it's worth, I ran into a [similar issue with Paperclip.](https://github.com/thoughtbot/paperclip/issues/1884)

**Comment by timfjord** [comment]
@bjmc Thanks for the suggestion.
It would be really great if you submit a PR with this feature.
From my side, I will keep this feature in the mind when i start working on gem improvement.

**Comment by KBalderson** [comment]
@timsly I ran into a tangentially related issue with base64 data. It is that the regex parser loads the entire base64 encoded string into memory as it parses, causing memory issues. I believe that adding the [data_uri](https://github.com/dball/data_uri) and using it in CarrierWave::DataUri::Parser#initialize will alleviate these issues. Would you be willing to add the data_uri gem as a dependency in order to get the more complete functionality?

**Comment by KBalderson** [comment]
I created a #9 to address this issue.

**Comment by timfjord** [comment]
Closing this one, because #9 is in the master right now.
@bjmc, if it still not working, feel free to reopen this issue
